# Generated by Django 2.0.7 on 2021-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1200, unique=True)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=200, null=True)),
                ('server_name', models.CharField(blank=True, max_length=600)),
                ('server_cpu_number', models.IntegerField(blank=True, null=True)),
                ('server_cpu_usage', models.IntegerField(blank=True, null=True)),
                ('server_memory_usage', models.IntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('load', models.IntegerField(default=0)),
                ('command_runner_version', models.CharField(blank=True, max_length=400, null=True)),
                ('problem', models.ManyToManyField(blank=True, to='problem.Problem')),
            ],
        ),
    ]
