# Generated by Django 2.0.7 on 2021-05-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeserver',
            name='load',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='server_cpu_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='server_cpu_usage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='server_memory_usage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
